pipeline:
  # Build base image to build from
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/postgis
    context: 10-2.5/
    tags: 10
    dockerfile: 10-2.5/Dockerfile
    when:
      event: push
  docker-alpine:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/postgis
    context: 10-2.5/alpine/
    tags: 10-alpine
    dockerfile: 10-2.5/alpine/Dockerfile
    when:
      event: push
